name: open-swe-justbuild
region: nyc
domains:
  - domain: justbuild.everjust.com
    type: PRIMARY

services:
  # Next.js Web Frontend
  - name: web
    github:
      repo: ever-just/JUSTBUILD2.0
      branch: main
      deploy_on_push: true
    build_command: yarn install --frozen-lockfile && yarn workspace @open-swe/web build
    run_command: yarn workspace @open-swe/web start
    source_dir: /
    environment_slug: node-js
    instance_size_slug: professional-xs
    instance_count: 1
    http_port: 3000
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://justbuild.everjust.com/api/agent
      - key: NEXT_PUBLIC_GITHUB_APP_CLIENT_ID
        value: "${GITHUB_APP_CLIENT_ID}"
        type: SECRET
      - key: GITHUB_APP_CLIENT_SECRET
        value: "${GITHUB_APP_CLIENT_SECRET}"
        type: SECRET
      - key: GITHUB_APP_ID
        value: "${GITHUB_APP_ID}"
        type: SECRET
      - key: GITHUB_APP_PRIVATE_KEY
        value: "${GITHUB_APP_PRIVATE_KEY}"
        type: SECRET
      - key: GITHUB_APP_REDIRECT_URI
        value: https://justbuild.everjust.com/api/auth/github/callback
      - key: NEXT_PUBLIC_GITHUB_APP_NAME
        value: JUSTBUILD
      - key: GITHUB_APP_NAME
        value: JUSTBUILD
      - key: SECRETS_ENCRYPTION_KEY
        value: "${SECRETS_ENCRYPTION_KEY}"
        type: SECRET
      - key: POSTHOG_API_KEY
        value: "${POSTHOG_API_KEY}"
        type: SECRET
      - key: POSTHOG_PROJECT_ID
        value: "${POSTHOG_PROJECT_ID}"
        type: SECRET
      - key: LANGFUSE_PUBLIC_KEY
        value: "${LANGFUSE_PUBLIC_KEY}"
        type: SECRET
      - key: LANGFUSE_SECRET_KEY
        value: "${LANGFUSE_SECRET_KEY}"
        type: SECRET
      - key: LANGCHAIN_API_KEY
        value: "${LANGCHAIN_API_KEY}"
        type: SECRET
      - key: LANGCHAIN_TRACING_V2
        value: "false"

  # LangGraph Agent Backend
  - name: agent
    github:
      repo: ever-just/JUSTBUILD2.0
      branch: main
      deploy_on_push: true
    build_command: yarn install --frozen-lockfile && yarn workspace @open-swe/agent build
    run_command: yarn workspace @open-swe/agent dev
    source_dir: /
    environment_slug: node-js
    instance_size_slug: professional-xs
    instance_count: 1
    http_port: 2024
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "2024"
      - key: GITHUB_APP_ID
        value: "${GITHUB_APP_ID}"
        type: SECRET
      - key: GITHUB_APP_PRIVATE_KEY
        value: "${GITHUB_APP_PRIVATE_KEY}"
        type: SECRET
      - key: GITHUB_WEBHOOK_SECRET
        value: "${GITHUB_WEBHOOK_SECRET}"
        type: SECRET
      - key: GITHUB_APP_NAME
        value: JUSTBUILD
      - key: SECRETS_ENCRYPTION_KEY
        value: "${SECRETS_ENCRYPTION_KEY}"
        type: SECRET
      - key: LANGCHAIN_API_KEY
        value: "${LANGCHAIN_API_KEY}"
        type: SECRET
      - key: LANGCHAIN_TRACING_V2
        value: "false"
      - key: DAYTONA_API_KEY
        value: "${DAYTONA_API_KEY}"
        type: SECRET
      - key: OPEN_SWE_LOCAL_MODE
        value: "false"
      - key: OPENAI_API_KEY
        value: "${OPENAI_API_KEY}"
        type: SECRET
      - key: ANTHROPIC_API_KEY
        value: "${ANTHROPIC_API_KEY}"
        type: SECRET
      - key: GOOGLE_GEMINI_API_KEY
        value: "${GOOGLE_GEMINI_API_KEY}"
        type: SECRET
      - key: FIREWORKS_API_KEY
        value: "${FIREWORKS_API_KEY}"
        type: SECRET
      - key: FIRECRAWL_API_KEY
        value: "${FIRECRAWL_API_KEY}"
        type: SECRET

ingress:
  rules:
    - match:
        path:
          prefix: "/api/agent"
      component:
        name: agent
        rewrite: "/"
    - match:
        path:
          prefix: "/"
      component:
        name: web
