[phases.setup]
nixPkgs = ["nodejs-18_x", "yarn-1_x"]

[phases.install]
cmds = [
    "npm install -g corepack@0.29.4",
    "corepack enable",
    "corepack prepare yarn@3.5.1 --activate"
]

[phases.build]
cmd = "bash scripts/railway-build.sh"

[start]
cmd = "yarn workspace @open-swe/agent dev"